### ISSUE TITLE
how can i access the api via node or simply with curl / rest ?

### ISSUE THREAD

**Issue by jpca999** [SimplyRETS/examples#1]
where can i get the examples for that ?

**Comment by CodyReichert** [comment]
@jpca999 - thanks for the issue. I've added some links to a few other examples in the README here: https://github.com/SimplyRETS/examples#more-resources

Particularly, there are some cURL examples at the bottom of [this page](https://docs.simplyrets.com) that should help.

**Comment by jpca999** [comment]
I appreciate that, but I can't find an api to get the  phone number of the current Realtor for the property ?  
2) Also how to find if the property is under contract or available ?
3) And the Email address of the Realtor. 

Where can i find these parameters ?
