### ISSUE TITLE
how do i provide info on which area / zip code listing is need on your api ?

### ISSUE THREAD

**Issue by jpca999** [SimplyRETS/examples#2]
on this link below you've the demo documentation for calling listing addersses, but i dont get how does the api provides like which zipcode or area code listigns is called for ?

https://simplyrets.com/blog/api-pagination.html

**Comment by CodyReichert** [comment]
Hey @jpca999 - the demo credentials have a set of 'dummy' listings associated with them (55 demo listings) -- that's where it's getting the address/postalCodes/etc.

Check out the FAQ for some more info on that and how to set up live data: https://simplyrets.com/faq
